#include <doctest/doctest.h>

#include <cmath>
#include <iterator>
#include <vector>

#include "kernels/kernels.h"

namespace {

void expect_close(std::span<const float> actual, std::span<const float> expected, float tol) {
    REQUIRE(actual.size() == expected.size());
    for (size_t i = 0; i < actual.size(); ++i) {
        CAPTURE(i);
        CHECK(std::abs(actual[i] - expected[i]) < tol);
    }
}

// Generated by scripts/fixtures.py -- do not edit by hand.
// Regenerate: python scripts/fixtures.py --seed 0
//
// Tolerances: 1e-5 for linear, 1e-6 for everything else, and see the rope
// block for why that one needs a per-position tolerance.

// ----------------------------------------------------------------------
// linear -- y = W * x + bias
// ----------------------------------------------------------------------
// Case 1 -- hand-checkable. W is 1..12 and x is all ones, so y[o] is
// (the sum of row o) + 0.5:  10.5, 26.5, 42.5. Verify it on paper once.

constexpr std::size_t kLinearOut = 3;
constexpr float kLinearWeights[] = {1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f, 7.0f, 8.0f, 9.0f,
    10.0f, 11.0f, 12.0f};  // [3, 4]
constexpr float kLinearX[] = {1.0f, 1.0f, 1.0f, 1.0f};  // [4]
constexpr float kLinearBias[] = {0.5f, 0.5f, 0.5f};  // [3]
constexpr float kLinearExpected[] = {10.5f, 26.5f, 42.5f};  // [3]

// Case 2 -- random, pass bias = nullptr. Tolerance 1e-5: accumulation order
// differs from NumPy's, and that is fine.

constexpr std::size_t kLinearOut2 = 5;
constexpr float kLinearWeights2[] = {1.11762202f, -1.3871249f, -0.426571608f,
    -0.803587258f, 0.601427734f, -0.0749932453f, 0.0596931949f, -0.0320060886f,
    -0.185484678f, 1.20477366f, 0.777453065f, -1.35828102f, 0.769827843f, -0.870226979f,
    1.09976351f, -0.958474219f, -1.27493191f, -1.36533809f, -1.47432756f, 0.433531702f,
    -0.328120619f, -0.970968008f, 1.26550245f, 0.00376360677f, -1.06654119f, 1.72889876f,
    -0.451382279f, 0.04862817f, -1.13824058f, -0.338293284f, -1.52973986f, 0.204066992f,
    -0.0536706373f, -0.906851947f, -0.0210764054f};  // [5, 7]
constexpr float kLinearX2[] = {-1.24412775f, 0.0832168758f, -0.247116044f, 1.31458926f,
    0.920494974f, -0.228772566f, -0.0304026175f};  // [7]
constexpr float kLinearExpected2[] = {-1.88791849f, -0.651252405f, -4.37412574f,
    1.60355383f, 2.19295259f};  // [5]

// ----------------------------------------------------------------------
// rmsnorm -- y_i = w_i * x_i / sqrt(mean(x^2) + eps)   [from HF]
// ----------------------------------------------------------------------
// Generated with transformers 4.57.6, eps = 1e-06.
// checked vs the documented formula: max|diff| = 6.22e-08 (< 1e-06)
//
// There is no mean subtraction and no bias -- this is RMS norm, not LayerNorm.

constexpr std::size_t kRmsNormN = 4;
constexpr float kRmsNormWeight[] = {1.0f, 2.0f, 0.5f, -1.0f};  // [4]
constexpr float kRmsNormX[] = {1.0f, -2.0f, 3.0f, 0.25f};  // [4]
constexpr float kRmsNormExpected[] = {0.533333242f, -2.13333297f, 0.799999833f, -0.13333331f};  // [4]

// Tiny-input case: mean(x^2) ~ 1e-16, so eps dominates. If this and the case
// above both pass, eps is inside the sqrt.

constexpr float kRmsNormXTiny[] = {9.99999994e-09f, -9.99999994e-09f, 1.99999999e-08f, 0.0f};  // [4]
constexpr float kRmsNormExpectedTiny[] = {9.99999975e-06f, -1.99999995e-05f,
    9.99999975e-06f, -0.0f};  // [4]

// ----------------------------------------------------------------------
// softmax -- x_i <- exp(x_i - max) / sum(exp(x_j - max))   [in place]
// ----------------------------------------------------------------------
// Case 2 is the whole test. It is case 1 shifted by +1000, so the correct answer
// is IDENTICAL -- but a softmax without the max-subtraction computes exp(1002),
// which overflows fp32 (the limit is ~88.7) and yields inf/inf = nan.

constexpr float kSoftmaxX[] = {1.0f, 2.0f, 3.0f};  // [3]
constexpr float kSoftmaxExpected[] = {0.0900305732f, 0.244728471f, 0.665240956f};  // [3]

constexpr float kSoftmaxXShifted[] = {1000.0f, 1001.0f, 1002.0f};  // [3] -- expects kSoftmaxExpected

// Degenerate n = 1: must be exactly 1.0. It runs on every first token.

constexpr float kSoftmaxXSingle[] = {5.0f};  // [1]
constexpr float kSoftmaxExpectedSingle[] = {1.0f};  // [1]

// Wider spread, the realistic case -- attention scores reach the tens.

constexpr float kSoftmaxXWide[] = {11.1762199f, -13.8712492f, -4.26571608f, -8.03587246f,
    6.01427746f, -0.749932468f, 0.596931934f, -0.320060879f};  // [8]
constexpr float kSoftmaxExpectedWide[] = {0.994260157f, 1.31680784e-11f, 1.95502554e-07f,
    4.50603252e-09f, 0.00569766486f, 6.57715164e-06f, 2.52914444e-05f, 1.01094776e-05f};  // [8]

// ----------------------------------------------------------------------
// rope -- split-half rotary embedding, per 64-wide head   [from HF]
// ----------------------------------------------------------------------
// Generated with transformers 4.57.6, theta = 1e+06.
// checked vs the documented formula: max|diff| = 1.01e-07 (< 1e-06)
//
// Element j pairs with element j + 32 -- half a head away, NOT the adjacent
// (2j, 2j+1) of the original paper.
//
// USE A PER-POSITION TOLERANCE. angle = pos * inv_freq, so the fp32 relative
// error in inv_freq (~6e-8) becomes an absolute angle error of ~pos * 6e-8
// radians:
// pos 0     max|diff| = 0.00e+00   -> test at 1e-07
// pos 3     max|diff| = 1.01e-07   -> test at 1e-06
// pos 1000  max|diff| = 3.31e-05   -> test at 1e-04

constexpr float kRopeTheta = 1000000.0f;  // read it from ModelConfig, not from here
constexpr float kRopeX[] = {1.11762202f, -1.3871249f, -0.426571608f, -0.803587258f,
    0.601427734f, -0.0749932453f, 0.0596931949f, -0.0320060886f, -0.185484678f,
    1.20477366f, 0.777453065f, -1.35828102f, 0.769827843f, -0.870226979f, 1.09976351f,
    -0.958474219f, -1.27493191f, -1.36533809f, -1.47432756f, 0.433531702f, -0.328120619f,
    -0.970968008f, 1.26550245f, 0.00376360677f, -1.06654119f, 1.72889876f, -0.451382279f,
    0.04862817f, -1.13824058f, -0.338293284f, -1.52973986f, 0.204066992f, -0.0536706373f,
    -0.906851947f, -0.0210764054f, -1.24412775f, 0.0832168758f, -0.247116044f, 1.31458926f,
    0.920494974f, -0.228772566f, -0.0304026175f, 0.00735633401f, -0.164132237f,
    -0.0150977643f, 1.22743702f, 1.04080665f, 0.679934442f, 0.251833498f, 1.66519105f,
    1.0347178f, -0.381819338f, -0.350518584f, 1.22865343f, -0.358671784f, -1.91329336f,
    1.02716708f, -1.35516644f, -1.67146826f, -1.05700147f, -1.32224083f, 0.773605883f,
    -1.72518516f, -0.1460547f};  // [64] -- the same input at all three positions

// pos = 0 makes every angle 0, so cos = 1, sin = 0 and rope is the IDENTITY --
// the expected output is kRopeX, unchanged.
constexpr size_t kRopePos0 = 0;

constexpr size_t kRopePos3 = 3;
constexpr float kRopeExpectedPos3[] = {-1.09886348f, 1.354146f, -0.108284928f,
    0.363605857f, 0.475534946f, 0.0133695155f, -0.235063553f, -0.165662676f, -0.162979886f,
    1.20436001f, 0.776536763f, -1.35355914f, 0.76997298f, -0.883621335f, 1.09233141f,
    -0.961605132f, -1.27568173f, -1.36857951f, -1.47563541f, 0.433845252f, -0.32793358f,
    -0.971393585f, 1.26558316f, 0.00404312043f, -1.06663859f, 1.72898221f, -0.451315403f,
    0.0486556292f, -1.13821828f, -0.338301748f, -1.52972758f, 0.204067662f, 0.210852355f,
    -0.955397606f, -0.413136721f, -1.43575668f, 0.377500832f, -0.25789839f, 1.29477918f,
    0.906030476f, -0.245314106f, 0.0438291058f, 0.0384446643f, -0.199359566f,
    -0.00210905261f, 1.21783006f, 1.04860413f, 0.67549926f, 0.248007581f, 1.66252792f,
    1.03285182f, -0.381463051f, -0.350693613f, 1.2283169f, -0.358387083f, -1.91329277f,
    1.02706587f, -1.35505998f, -1.67148626f, -1.05700016f, -1.32226002f, 0.773602188f,
    -1.725196f, -0.146053761f};  // [64] at pos 3

constexpr size_t kRopePos1000 = 1000;
constexpr float kRopeExpectedPos1000[] = {0.672906399f, 1.55734253f, -0.305882812f,
    0.0741288662f, -0.27250725f, 0.224693745f, 0.577341437f, 0.920426786f, -0.134545416f,
    -0.107921198f, 0.553652167f, 1.09339678f, 0.59901154f, 1.35878885f, -1.51407003f,
    -0.709193707f, -0.90075922f, -2.09436536f, -1.76868963f, 0.520634115f, -0.260942221f,
    -1.10606873f, 1.28881729f, 0.0968935043f, -1.0984844f, 1.75636089f, -0.429053396f,
    0.0577794909f, -1.13078713f, -0.341116011f, -1.52564454f, 0.204291672f, 0.893955529f,
    -0.566727698f, -0.298065871f, 1.47922647f, 0.542568147f, 0.127291203f, 1.18253326f,
    0.033909902f, -0.261990428f, 1.20031536f, 0.545854032f, -0.8224051f, -0.483785123f,
    -0.646211624f, 0.0187091827f, -0.937031507f, -0.936751962f, 0.500642836f, 0.340616822f,
    -0.250351459f, -0.403032959f, 1.1085937f, -0.262853414f, -1.91084194f, 0.992932141f,
    -1.31937981f, -1.67733872f, -1.05654085f, -1.32862067f, 0.772365332f, -1.72880781f,
    -0.145740271f};  // [64] at pos 1000

// ----------------------------------------------------------------------
// silu_mul -- gate_i <- silu(gate_i) * up_i,  silu(z) = z / (1 + e^-z)
// ----------------------------------------------------------------------
// Case 1 -- up is all ones, isolating silu. Includes +-100: for very negative z,
// e^-z overflows to inf and z/inf gives -0, which is the correct limit; for very
// positive z, e^-z underflows to 0 and the result is z. Both correct, so the
// kernel needs NO clamping.

constexpr std::size_t kSiluN = 9;
constexpr float kSiluGate[] = {0.0f, 1.0f, -1.0f, 5.0f, -5.0f, 0.5f, -0.5f, 100.0f, -100.0f};  // [9]
constexpr float kSiluUpOnes[] = {1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f};  // [9]
constexpr float kSiluExpected[] = {0.0f, 0.731058579f, -0.268941421f, 4.96653575f,
    -0.0334642546f, 0.311229666f, -0.188770334f, 100.0f, -3.72007598e-42f};  // [9]

// Case 2 -- real random vectors. silu applies to GATE and the result multiplies
// UP; swapping them is silent and wrong.

constexpr float kSiluGate2[] = {1.11762202f, -1.3871249f, -0.426571608f, -0.803587258f,
    0.601427734f, -0.0749932453f, 0.0596931949f, -0.0320060886f};  // [8]
constexpr float kSiluUp2[] = {-0.185484678f, 1.20477366f, 0.777453065f, -1.35828102f,
    0.769827843f, -0.870226979f, 1.09976351f, -0.958474219f};  // [8]
constexpr float kSiluExpected2[] = {-0.156211693f, -0.33401229f, -0.130979423f,
    0.337555034f, 0.299087371f, 0.0314076095f, 0.0338035987f, 0.0150930636f};  // [8]

// ----------------------------------------------------------------------
// argmax -- index of the largest element, ties to the LOWEST index
// ----------------------------------------------------------------------
// The tie case pins the behavior NumPy and torch have, which is what parity
// compares against: a strict > comparison (never >=) gives it for free.

constexpr float kArgmaxX[] = {0.100000001f, 0.899999976f, 0.300000012f};  // [3]
constexpr std::size_t kArgmaxExpected = 1;

constexpr float kArgmaxXTie[] = {3.0f, 3.0f, 1.0f};  // [3] -- both 3.0
constexpr std::size_t kArgmaxExpectedTie = 0;

constexpr float kArgmaxXWide[] = {1.11762202f, -1.3871249f, -0.426571608f, -0.803587258f,
    0.601427734f, -0.0749932453f, 0.0596931949f, -0.0320060886f, -0.185484678f,
    1.20477366f, 0.777453065f, -1.35828102f, 0.769827843f, -0.870226979f, 1.09976351f,
    -0.958474219f};  // [16]
constexpr std::size_t kArgmaxExpectedWide = 9;

}  // namespace

// ---------------------------------------------------------------- linear

TEST_CASE("linear computes W*x + bias on a hand-checkable case") {
    std::vector<float> y(kLinearOut);
    linear(y, kLinearX, kLinearWeights, kLinearBias);
    expect_close(y, kLinearExpected, 1e-5f);
}

TEST_CASE("linear matches NumPy on a random case with bias = nullptr") {
    std::vector<float> y(kLinearOut2);
    linear(y, kLinearX2, kLinearWeights2, nullptr);
    expect_close(y, kLinearExpected2, 1e-5f);
}

TEST_CASE("linear rejects weights whose flattened size disagrees with x and y") {
    std::vector<float> y(kLinearOut);
    std::vector<float> w(std::size(kLinearWeights) - 1);
    CHECK_THROWS_AS(linear(y, kLinearX, w, nullptr), std::runtime_error);
}

// ---------------------------------------------------------------- rmsnorm

TEST_CASE("rmsnorm matches Hugging Face's Qwen2RMSNorm") {
    std::vector<float> y(kRmsNormN);
    rmsnorm(y, kRmsNormX, kRmsNormWeight, 1e-6f);
    expect_close(y, kRmsNormExpected, 1e-6f);
}

TEST_CASE("rmsnorm keeps eps inside the sqrt, verified on tiny inputs") {
    std::vector<float> y(kRmsNormN);
    rmsnorm(y, kRmsNormXTiny, kRmsNormWeight, 1e-6f);
    expect_close(y, kRmsNormExpectedTiny, 1e-6f);
}

TEST_CASE("rmsnorm rejects mismatched x/y/weights sizes") {
    std::vector<float> y(kRmsNormN);
    std::vector<float> w(kRmsNormN - 1);
    CHECK_THROWS_AS(rmsnorm(y, kRmsNormX, w, 1e-6f), std::runtime_error);
}

// ---------------------------------------------------------------- softmax

TEST_CASE("softmax matches the plain formula and is unchanged by a +1000 shift") {
    std::vector<float> x(std::begin(kSoftmaxX), std::end(kSoftmaxX));
    softmax(x);
    expect_close(x, kSoftmaxExpected, 1e-6f);

    std::vector<float> shifted(std::begin(kSoftmaxXShifted), std::end(kSoftmaxXShifted));
    softmax(shifted);
    for (float v : shifted) CHECK(std::isfinite(v));
    expect_close(shifted, kSoftmaxExpected, 1e-6f);
}

TEST_CASE("softmax on a single element is exactly 1") {
    std::vector<float> x(std::begin(kSoftmaxXSingle), std::end(kSoftmaxXSingle));
    softmax(x);
    expect_close(x, kSoftmaxExpectedSingle, 1e-6f);
}

TEST_CASE("softmax matches NumPy on a wider spread") {
    std::vector<float> x(std::begin(kSoftmaxXWide), std::end(kSoftmaxXWide));
    softmax(x);
    expect_close(x, kSoftmaxExpectedWide, 1e-6f);
}

TEST_CASE("softmax on an empty span is a no-op") {
    std::vector<float> x;
    softmax(x);
    CHECK(x.empty());
}

// ---------------------------------------------------------------- rope

TEST_CASE("rope at pos 0 is the identity") {
    std::vector<float> v(std::begin(kRopeX), std::end(kRopeX));
    rope(v, kRopePos0, kRopeTheta);
    expect_close(v, kRopeX, 1e-7f);
}

TEST_CASE("rope matches Hugging Face's apply_rotary_pos_emb at pos 3") {
    std::vector<float> v(std::begin(kRopeX), std::end(kRopeX));
    rope(v, kRopePos3, kRopeTheta);
    expect_close(v, kRopeExpectedPos3, 1e-6f);
}

TEST_CASE("rope matches Hugging Face at pos 1000, where fp32 angle error grows") {
    std::vector<float> v(std::begin(kRopeX), std::end(kRopeX));
    rope(v, kRopePos1000, kRopeTheta);
    expect_close(v, kRopeExpectedPos1000, 1e-4f);
}

TEST_CASE("rope rejects an odd-sized vector") {
    std::vector<float> v(std::size(kRopeX) - 1, 0.0f);
    CHECK_THROWS_AS(rope(v, kRopePos3, kRopeTheta), std::runtime_error);
}

// ---------------------------------------------------------------- silu_mul

TEST_CASE("silu_mul with up = 1 isolates the activation, including the overflow edges") {
    std::vector<float> gate(std::begin(kSiluGate), std::end(kSiluGate));
    silu_mul(gate, kSiluUpOnes);
    expect_close(gate, kSiluExpected, 1e-6f);
}

TEST_CASE("silu_mul applies SiLU to gate and multiplies by up, not the reverse") {
    std::vector<float> gate(std::begin(kSiluGate2), std::end(kSiluGate2));
    silu_mul(gate, kSiluUp2);
    expect_close(gate, kSiluExpected2, 1e-6f);
}

TEST_CASE("silu_mul rejects mismatched gate/up sizes") {
    std::vector<float> gate(kSiluN);
    std::vector<float> up(kSiluN - 1);
    CHECK_THROWS_AS(silu_mul(gate, up), std::runtime_error);
}

// ---------------------------------------------------------------- argmax

TEST_CASE("argmax finds the largest element") {
    CHECK(argmax(kArgmaxX) == kArgmaxExpected);
}

TEST_CASE("argmax resolves ties to the lowest index") {
    CHECK(argmax(kArgmaxXTie) == kArgmaxExpectedTie);
}

TEST_CASE("argmax matches NumPy on a wider vector") {
    CHECK(argmax(kArgmaxXWide) == kArgmaxExpectedWide);
}

TEST_CASE("argmax rejects an empty span") {
    std::vector<float> empty;
    CHECK_THROWS_AS(argmax(empty), std::runtime_error);
}

TEST_CASE("argmax rejects a nan winner instead of silently returning index 0") {
    std::vector<float> x{std::nanf(""), std::nanf("")};
    CHECK_THROWS_AS(argmax(x), std::runtime_error);
}
